### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by inxomnyaa** [jasonwynn10/CrashAndBan#1]
Instead of a task, you could do it on PlayerJoinEvent
You could also just send a packet to change the skin, this is far less complex and works great too for crashing the client. Could reduce the code by alot and works for any version since 1.1

**Comment by jasonw4331** [comment]
That doesn't work because player join event is never triggered for banned players

**Comment by inxomnyaa** [comment]
Cancel the kick, then do it on join?

**Comment by jasonw4331** [comment]
might as well do it on kick like I am
